apps/todo/models.py
from flask_login import UserMixin
from werkzeug.security import (
    generate_password_hash,
    check_password_hash
    )
from flask_sqlalchemy import SQLAlchemy
db = SQLAlchemy()


class Todo(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(255), default="")
    text = db.Column(db.Text, default="")

    def __init__(self, title, text):
        self.title = title
        self.text = text


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    password_hash = db.Column(db.String(128))

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

apps/todo/views/forms.py
from wtforms import Form, StringField, PasswordField, validators


class LoginForm(Form):
    username = StringField('username', [validators.Length(min=4, max=25)])
    password = PasswordField('password', [
        validators.InputRequired(),
        validators.EqualTo('confirm', message='Passwords must match')
    ])


class TodoForm(Form):
    title = StringField('title', [
        validators.required(),
        validators.Length(min=4, max=100)
    ])

    text = StringField('text', [
        validators.required(),
        validators.Length(min=4, max=300)
    ])

apps/todo/views/todo.py
from flask import Blueprint
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask import session
from flask import abort
from apps.todo.views.forms import LoginForm, TodoForm
from flask_login import login_user, login_required, logout_user, LoginManager
from apps.todo.models import Todo, User, db


login_manager = LoginManager()

todo = Blueprint('todo', __name__)


@login_manager.user_loader
def load_user(id):
    if id is None:
        redirect('/login')
    user = User.query.filter(User.id == id).first()
    if user:
        return user
    else:
        return None


@todo.route('/show_entries')
def show_entries():
    entries = Todo.query.order_by(Todo.id.desc()).all()
    return render_template('show_entries.html', entries=entries)


@todo.route('/add', methods=['POST'])
def add_entry():
    if not session.get('logged_in'):
        abort(401)
    form = TodoForm(request.form)
    if request.method == 'POST' and form.validate():
        db.session.add(Todo(title=request.form['title'], text=request.form['text']))
        db.session.commit()
        flash('成功推送新的任务！')
        return redirect(url_for('todo.show_entries'))
    else:
        flash('请填写标题和内容！')
        return redirect(url_for('todo.show_entries'))


@todo.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        user = User.query.filter(User.username == username).first()
        if user:
            form = LoginForm(request.form)
            if form:
                # 将用户信息注册到flask-login中,*******重要
                login_user(user)

                if user.check_password(password):
                    session['logged_in'] = True
                    flash('你已经登录了')
                    return redirect(url_for('todo.show_entries'))
                else:
                    error = '密码不正确'
            else:
                error = '请填写内容'
        else:
            u = User()
            u.username = username
            u.set_password(password)
            db.session.add(u)
            db.session.commit()
            error = "用户名已经建立"

    return render_template('login.html', error=error)


@todo.route('/logout')
@login_required
def logout():
    logout_user()
    session.pop('logged_in', None)
    flash('你已经登出了')
    return redirect(url_for('todo.show_entries'))


@todo.route('/delete', methods=['GET'])
def delete():
    if not session.get('logged_in'):
        abort(401)
    entry = Todo.query.get(request.args.get("id"))
    db.session.delete(entry)
    db.session.commit()
    flash('成功移除任务')
    return redirect(url_for('todo.show_entries'))


@todo.errorhandler(400)
def handler(exception):

    return '捕获到异常信息:%s' % exception


@todo.route('/make_abort/')
def get_abort():
    abort(400)
    return '终止'

templates/layout.html
<!doctype html>
<title>Todo List</title>
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='style.css') }} ">
<div class=page>
  <h1>任务清单</h1>
  <div class=metanav>
  {% if not session.logged_in %}
    <a href="{{ url_for('todo.login') }}">登录</a>
  {% else %}
    <a href="{{ url_for('todo.logout') }}">注销</a>
  {% endif %}
  {% if current_user.is_authenticated  %}
       {{ current_user.username }}
  {% else %}
    none
 {% endif %}
  </div>
  {% for message in get_flashed_messages() %}
    <div class=flash>{{ message }}</div>
  {% endfor %}
  {% block body %}{% endblock %}
</div>

templates/login.html
{% extends "layout.html" %}
{% block body %}
  <h2>Login</h2>
  {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
  <form action="{{ url_for('todo.login') }}" name="LoginForm" method=post>
    <dl>
      <dt>用户名:
      <dd><input type=text name=username>
      <dt>密 码:
      <dd><input type=password name=password>
      <dd><input type= submit value=Login>
    </dl>
  </form>
{% endblock %}

templates/show_entries.html
{% extends "layout.html" %}
{% block body %}
  {% if session.logged_in %}
    <form action="{{ url_for('todo.add_entry') }}" method=post class=add-entry>
      <dl>
        <dt>标题:
        <dd><input type=text size=30 name=title>
        <dt>内容:
        <dd><textarea name=text rows=5 cols=40></textarea>
        <dd><input type=submit value=添加>
      </dl>
    </form>
  {% endif %}
  <ul class=entries>
  {% for entry in entries %}
    <li><h2>{{ entry.title }}  <a href="{{ url_for('todo.delete') }}?id={{ entry.id }}">移除</a></h2>{{ entry.text|safe }}

  {% else %}
    <li><em>暂无内容！</em>
  {% endfor %}
  </ul>
{% endblock %}